# Generated by Django 6.0.3 on 2026-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('course', models.CharField(max_length=100, verbose_name='Course')),
                ('semester', models.CharField(max_length=50, verbose_name='Semester')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
        ),
    ]
