# Generated by Django 6.0.3 on 2026-04-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da imagem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='NOme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(max_length=50, verbose_name='Período'),
        ),
    ]
