# Generated by Django 6.0.3 on 2026-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição do Certificado')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('PERSONAL', 'Projeto Pessoal'), ('COURSE', 'Projeto de Disciplina'), ('FREELANCER', 'Freelancer')], default='PERSONAL', max_length=20, verbose_name='Tipo de Projeto')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('description', models.TextField(verbose_name='Descrição do Projeto')),
                ('github_url', models.URLField(verbose_name='Link do GitHub')),
            ],
        ),
    ]
