# Generated by Django 6.0.3 on 2026-06-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='Task',
        ),
    ]
